name: WorkflowNotification

on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

workflow_dispach:

  jobs:
    job01: 
    #onde sera iniciado 
     runs-on: ubuntu-latest
     steps:
       - uses: action/checkout@v3
       - name : Run a one-line script
         run: echo Olá mundo!
